apiVersion: apps/v1
kind: Deployment
metadata:
  name: broken-app
  labels:
    app: broken-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broken-app
  template:
    metadata:
      labels:
        app: broken-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest  # Fixed image tag
        ports:
        - containerPort: 80
        env:
        - name: REQUIRED_VAR
          value: "default-value"  # Fixed environment variable 